version: 2

# Set the version of Python and install requirements
python:
  version: "3.10"  # Specify the Python version
  install:
    - requirements: requirements.txt
    - method: pip
      path: .

# Sphinx configuration
sphinx:
  configuration: docs/conf.py

# Optionally, you can add build.os if you need to specify the operating system
# This key might not be necessary for your use case
build:
  os: "ubuntu-22.04"
