# .readthedocs.yml

version: 2

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.8  # Specify the Python version
  install:
    - requirements: requirements.txt
    - method: pip
      path: .

sphinx:
  builder: html
  configuration: docs/conf.py
